export default [
    {
        img:"./p_bike images/mt-15-2-062e4b1bb4ffad.webp",
        name:" yamaha mt 15 v2",
        price:" 1.65-1.66 lakh*",
        capacity:"155CC",
        mileage:"50kmpl",
        tank_capacity:"10L",
    },
    {
        img:"./p_bike images/classic3506131bb8729f70.webp",
        name:" royal enfield classic",
        price:" 1.90-2.21 lakh*",
        capacity:"349.34CC",
        mileage:"41.55kmpl",
        tank_capacity:"13L ",
    },
    {
        img:"./p_bike images/m_ninja-h2_11540288231.webp",
        name:" Kawasaki Ninja H2",
        price:" 79.90 lakh*",
        capacity:"998CC",
        mileage:"15kmpl",
        tank_capacity:"17L",
    },
    {
        img:"./p_bike images/panigale-v4630dac4c64957.jpg",
        name:" Ducati Panigale V4",
        price:" 40 lakh*",
        capacity:"1103CC",
        mileage:"13kmpl",
        tank_capacity:"17L ",
    },
    {
        img:"./p_bike images/m_yzf-r1_11548224217.webp",
        name:"  Yamaha YZF R1",
        price:" 20.40 lakh*",
        capacity:"998CC",
        mileage:"20kmpl",
        tank_capacity:"17L",
    },
    {
        img:"./p_bike images/rocket-3635a7709a2a39.webp",
        name:"  Triumph Rocket 3 ",
        price:" 21.40 lakh*",
        capacity:"2458CC",
        mileage:"14.28kmpl",
        tank_capacity:"18L",
    },
    {
        img:"./p_bike images/m-1000-rr605c40f24db99.webp",
        name:" BMW M 1000 RR ",
        price:" 45 lakh*",
        capacity:"999CC",
        mileage:"15.6kmpl",
        tank_capacity:"16.5L",
    },
    {
        img:"./p_bike images/502-c614844649d8a5.webp",
        name:" BMW M 1100 RR ",
        price:" 47 lakh*",
        capacity:"1010CC",
        mileage:"17.6kmpl",
        tank_capacity:"12L",
    },
    {
        img:"./p_bike images/g-310-gs6076cf8e3b0de.webp",
        name:" BMW G 310 GS   ",
        price:" 3.15 Lakh",
        capacity:"313CC",
        mileage:"29.26kmpl",
        tank_capacity:"11L",
    },
    {
        img:"./p_bike images/tiger-1200628d8e4753823.webp",
        name:" Triumph Tiger 1200  ",
        price:" 19.19 - 21.69 Lakh",
        capacity:"1160CC",
        mileage:"19.60kmpl",
        tank_capacity:"30L",
    },
    {
        img:"./p_bike images/v-strom-25062e3d269d3a5e.webp",
        name:" Suzuki V-Strom SX ",
        price:" 2.12 Lakh*",
        capacity:"1160CC",
        mileage:"19.60kmpl",
        tank_capacity:"30L",
    },
    {
        img:"./p_bike images/kawasaki-100061a47216c935b.webp",
        name:" Kawasaki Ninja 1000",
        price:" 11.98 Lakh*",
        capacity:"1043CC",
        mileage:"9.5kmpl",
        tank_capacity:"19L",
    },
    {
        img:"./p_bike images/cb500x604f507aaecaf.webp",
        name:" Honda CB500X   ",
        price:" 5.80 Lakh*",
        capacity:"471.03CC",
        mileage:"11kmpl",
        tank_capacity:"17.7L",
    },
    {
        img:"./p_bike images/multistrada-v26156e0fa13725.webp",
        name:"  Ducati Multistrada",
        price:" 15.49 - 17.49 Lakh*",
        capacity:"937CC",
        mileage:"10kmpl",
        tank_capacity:"20.7L",
    },
    {
        img:"./p_bike images/f-850-gs-adventure625a40e11a02f.webp",
        name:" BMW F 850 GS ",
        price:" 13.25 Lakh*",
        capacity:"853CC",
        mileage:"11.5kmpl",
        tank_capacity:"23L",
    },
    {
        img:"./scooter images/x.pagespeed.ic.vYLHQ7kk5I.jpg",
        name:" honda activa 6g",
        price:" 73,531 on road*",
        capacity:"110CC",
        mileage:"50kmpl",
        tank_capacity:"5.3L",
    },
    {
        img:"./scooter images/x.pagespeed.ic.2WTHwbFWDZ.jpg",
        name:"  TVS ntorq 125 ",
        price:" 85,427 on road*",
        capacity:"124.8CC",
        mileage:"45 to 50kmpl",
        tank_capacity:"5.8L",
    },
    {
        img:"./scooter images/x.pagespeed.ic.w6wTJ2SyBl.jpg",
        name:" suzuki access ",
        price:" 85,427 on road*",
        capacity:"124.8CC",
        mileage:"50kmpl",
        tank_capacity:"5.8L",
    },
    {
        img:"./scooter images/x.pagespeed.ic.HVyOUw2Ndy.jpg",
        name:"  TVS JUPITER",
        price:" 73,097 on road*",
        capacity:"109.7CC",
        mileage:"50kmpl",
        tank_capacity:"7L",
    },
    {
        img:"./scooter images/x.pagespeed.ic.VF6KuEplL5.jpg",
        name:" Yamaha YZF R1   ",
        price:" 78,963 on road*",
        capacity:"125CC",
        mileage:"50.5kmpl",
        tank_capacity:"5.2L",
    },
    {
        img:"./scooter images/x.pagespeed.ic.uk7RC29IZI.jpg",
        name:" honda activa 125 ",
        price:" 78,084 on road*",
        capacity:"124CC",
        mileage:"46.5kmpl",
        tank_capacity:"5.3L",
    },
    {
        img:"./scooter images/x.pagespeed.ic.guYp9rBKBr.jpg",
        name:" honda dio  ",
        price:" 71,371 on road*",
        capacity:"109.51CC",
        mileage:"48kmpl",
        tank_capacity:"5.8L",
    },
    {
        img:"./scooter images/x.pagespeed.ic.EA0-R2GPLd.jpg",
        name:" Suzuki Burgman",
        price:" 89,298 on road*",
        capacity:"124CC",
        mileage:"50kmpl",
        tank_capacity:"5.5L",
    },
    {
        img:"./scooter images/download (1).jpeg",
        name:" hero maestro edge 125 ",
        price:" 82,196 on road*",
        capacity:"124.6CC",
        mileage:"45kmpl",
        tank_capacity:"5L",
    },
    {
        img:"./scooter images/x.pagespeed.ic.yKtRoIdPxD.jpg",
        name:" suzuki avenis 125",
        price:" 89,672 on road*",
        capacity:"124CC",
        mileage:"54kmpl",
        tank_capacity:"5.2L",
    },
    {
        img:"./scooter images/x.pagespeed.ic.pxGuCIv_sT.jpg",
        name:" tvs cooty zest 110 ",
        price:" 73,002 on road*",
        capacity:"109.7CCC",
        mileage:"45kmpl",
        tank_capacity:"5L",
    },
    {
        img:"./scooter images/x.pagespeed.ic.ZRBkQ5YaF6.jpg",
        name:" hero pleasure ",
        price:" 67,898 on road*",
        capacity:"110.9CC",
        mileage:"50kmpl",
        tank_capacity:"4.8L",
    },
    {
        img:"./scooter images/x.pagespeed.ic.2u0WT9HQsd.jpg",
        name:" tvs scooty pep plus ",
        price:" 63,514 on road*",
        capacity:" 87.8CC",
        mileage:"50kmpl",
        tank_capacity:"4.2L",
    },
    {
        img:"./scooter images/ray-zr-125619c74ef1b391.webp",
        name:"  yamaha rayzr 125  ",
        price:" 80,730 - 30,130on road*",
        capacity:"125CC",
        mileage:"50kmpl",
        tank_capacity:"20.7L",
    },
    {
        img:"./scooter images/destini-1256246b7719af18.webp",
        name:"hero destini-125 ",
        price:" 71,108 - 82,908 on road*",
        capacity:"124.6CC",
        mileage:"54kmpl",
        tank_capacity:"5L",
    },
    {
        img:"./e_bike images/appscooter62d909eb8f2cb.webp",
        name:" ola s1",
        price:" 79,999 - 1.40L*",
        Max_Speed:"116 kmph",
        Range: "181 km/charge",
        Battery_capacity:"4KWh",
    },
    {
        img:"./e_bike images/450x62d7dc5ebe639.webp",
        name:"ather 450X",
        price:" 1.17 - 1.39L*",
        Max_Speed:"80 kmph",
        Range: "146 km/charge",
        Battery_capacity:"3.7KWh",
    },
    {
        img:"./e_bike images/iqube-electric63368c7e20470.webp",
        name:" tvs iqube electric",
        price:" 1.61 lakh*",
        Max_Speed:"82kmph",
        Range: "145 km/charge",
        Battery_capacity:"4.56KWh",
    },
    {
        img:"./e_bike images/scooter634e6fdb95136.webp",
        name:" hero vida v1",
        price:" 1.39 lakh*",
        Max_Speed:"80kmph",
        Range: "165 km/charge",
        Battery_capacity:"3.94kwh",
    },
    {
        img:"./e_bike images/5e59f569b9ade.webp",
        name:" bajaj chetak",
        price:" 1.52 lakh*",
        Max_Speed:"63kmph",
        Range: "95 km/charge",
        Battery_capacity:"60.4kwh",
    },
    {
        img:"./e_bike images/mark-262de83797b0c7.webp",
        name:" simple-one",
        price:" 1.45 lakh*",
        Max_Speed:"105kmph",
        Range: "300+ km/charge",
        Battery_capacity:"4.8kwh",
    },
    {
        img:"./e_bike images/e-scooter623ead5d34de4.webp",
        name:" bounce infinty e1",
        price:" 70,499*",
        Max_Speed:"65kmph",
        Range: "85km/charge",
        Battery_capacity:"1.9kwh",
    },
    {
        img:"./e_bike images/heroelectric-optima60f512a4cd47f.webp",
        name:"  hero electric optima",
        price:" 85,190*",
        Max_Speed:"45kmph",
        Range: "140km/charge",
        Battery_capacity:"51.2v",
    },
    {
        img:"./e_bike images/magnus615192c194704.webp",
        name:" ampere maguns ex",
        price:" 77,249*",
        Max_Speed:"50kmph",
        Range: "121km/charge",
        Battery_capacity:"60v",
    },
    {
        img:"./e_bike images/praisepro604c5da5ae1e6.webp",
        name:" akinawa praise pro",
        price:" 99,645*",
        Max_Speed:"58kmph",
        Range: "88km/charge",
        Battery_capacity:"2.0kwh",
    },
    {
        img:"./e_bike images/heroelectric-nyx60f511826a2e0.webp",
        name:" hero electric nyx",
        price:" 86,540*",
        Max_Speed:"42kmph",
        Range: "100km/charge",
        Battery_capacity:"46v",
    },
    {
        img:"./e_bike images/hero-electric-photon60f513d69a903.webp",
        name:" hero electric photon",
        price:" 86,391*",
        Max_Speed:"45kmph",
        Range: "60km/charge",
        Battery_capacity:"72v",
    },
    {
        img:"./e_bike images/zoom61fcac0beb47d.webp",
        name:" kinetic-green zoom",
        price:" 82,500*",
        Max_Speed:"40kmph",
        Range: "100km/charge",
        Battery_capacity:"60v",
    },
    {
        img:"./e_bike images/reo5fbcd02994358.webp",
        name:" ampere reo",
        price:" 61,999*",
        Max_Speed:"25kmph",
        Range: "58km/charge",
        Battery_capacity:"48v",
    },
    {
        img:"./e_bike images/v_e-star-std1529918580.jpg",
        name:"  avon e star",
        price:" 60,000*",
        Max_Speed:"50kmph",
        Range: "65km/charge",
        Battery_capacity:"48v",
    },

]