export default [
    {
        img:"./deisel cars images/isu.webp",
        name:" isuzu d MAX",
        price:" 19 lakhs*",
        mileage:"  17 kmpl",
        transmission:"Manual&automatic",
        capacity:"5",
    },
    {
        img:"./deisel cars images/MercedesBenz-GClass-Exterior-137816.webp",
        name:"  mercedes G class",
        price:" 1.72 crore*",
        mileage:" 15 kmpl",
        transmission:"Manual",
        capacity:"4",
    },
    {
        img:"./deisel cars images/thar-exterior-right-front-three-quarter-11.webp",
        name:" mahindra thar",
        price:"  13.48 lakh*",
        mileage:" 15.2 kmpl",
        transmission:"Manual",
        capacity:"4",
    },
    {
        img:"./deisel cars images/hyundai-creta-right-front-three-quarter9.webp",
        name:" hyundei creta ",
        price:" 10.44 lakh*",
        mileage:"17-21 kmpl ",
        transmission:"Manual&automatic",
        capacity:"5",
    },
    {
        img:"./deisel cars images/fortuner-exterior-right-front-three-quarter-19.webp",
        name:" Toyota fortuner",
        price:" 38 Lakhs* ",
        mileage:" 10-14.4kmpl",
        transmission:"Manual&automatic",
        capacity:"7",
    },
    {
        img:"./deisel cars images/5-series-exterior-right-front-three-quarter-4.webp",
        name:" BMW 5 series ",
        price:" 65 lakhs",
        mileage:" 20 kmpl",
        transmission:"Manual&automatic",
        capacity:"5",
    },
    {
        img:"./deisel cars images/bolero-exterior-right-front-three-quarter.webp",
        name:" Mahindra Bolero",
        price:" 9.53 lakhs*",
        mileage:" 16 kmpl",
        transmission:"Manual",
        capacity:"7",
    },
    {
        img:"./deisel cars images/gls-exterior-right-front-three-quarter-2.webp",
        name:" mercedes-benz gls",
        price:" 1.16 crore*",
        mileage:" 12.5 kmpl",
        transmission:"automatic",
        capacity:"5",
    },
    {
        img:"./deisel cars images/scorpio-classic-exterior-right-front-three-quarter.webp",
        name:"  mahindra scopio ",
        price:" 12 lakhs*",
        mileage:" 15 kmpl",
        transmission:"Manual",
        capacity:"7-9",
    },
    {
        img:"./deisel cars images/MercedesBenz-GClass-Exterior-137816.webp",
        name:" mercedes C class",
        price:" 56 lakhs*",
        mileage:" 13 kmpl",
        transmission:"Manual&automatic",
        capacity:"4",
    },
]