export default [
    {
        img:"./e_bike images/appscooter62d909eb8f2cb.webp",
        name:" ola s1",
        price:" 79,999 - 1.40L*",
        Max_Speed:"116 kmph",
        Range: "181 km/charge",
        Battery_capacity:"4KWh",
    },
    {
        img:"./e_bike images/450x62d7dc5ebe639.webp",
        name:"ather 450X",
        price:" 1.17 - 1.39L*",
        Max_Speed:"80 kmph",
        Range: "146 km/charge",
        Battery_capacity:"3.7KWh",
    },
    {
        img:"./e_bike images/iqube-electric63368c7e20470.webp",
        name:" tvs iqube electric",
        price:" 1.61 lakh*",
        Max_Speed:"82kmph",
        Range: "145 km/charge",
        Battery_capacity:"4.56KWh",
    },
    {
        img:"./e_bike images/scooter634e6fdb95136.webp",
        name:" hero vida v1",
        price:" 1.39 lakh*",
        Max_Speed:"80kmph",
        Range: "165 km/charge",
        Battery_capacity:"3.94kwh",
    },
    {
        img:"./e_bike images/5e59f569b9ade.webp",
        name:" bajaj chetak",
        price:" 1.52 lakh*",
        Max_Speed:"63kmph",
        Range: "95 km/charge",
        Battery_capacity:"60.4kwh",
    },
    {
        img:"./e_bike images/mark-262de83797b0c7.webp",
        name:" simple-one",
        price:" 1.45 lakh*",
        Max_Speed:"105kmph",
        Range: "300+ km/charge",
        Battery_capacity:"4.8kwh",
    },
    {
        img:"./e_bike images/e-scooter623ead5d34de4.webp",
        name:" bounce infinty e1",
        price:" 70,499*",
        Max_Speed:"65kmph",
        Range: "85km/charge",
        Battery_capacity:"1.9kwh",
    },
    {
        img:"./e_bike images/heroelectric-optima60f512a4cd47f.webp",
        name:"  hero electric optima",
        price:" 85,190*",
        Max_Speed:"45kmph",
        Range: "140km/charge",
        Battery_capacity:"51.2v",
    },
    {
        img:"./e_bike images/magnus615192c194704.webp",
        name:" ampere maguns ex",
        price:" 77,249*",
        Max_Speed:"50kmph",
        Range: "121km/charge",
        Battery_capacity:"60v",
    },
    {
        img:"./e_bike images/praisepro604c5da5ae1e6.webp",
        name:" akinawa praise pro",
        price:" 99,645*",
        Max_Speed:"58kmph",
        Range: "88km/charge",
        Battery_capacity:"2.0kwh",
    },
    {
        img:"./e_bike images/heroelectric-nyx60f511826a2e0.webp",
        name:" hero electric nyx",
        price:" 86,540*",
        Max_Speed:"42kmph",
        Range: "100km/charge",
        Battery_capacity:"46v",
    },
    {
        img:"./e_bike images/hero-electric-photon60f513d69a903.webp",
        name:" hero electric photon",
        price:" 86,391*",
        Max_Speed:"45kmph",
        Range: "60km/charge",
        Battery_capacity:"72v",
    },
    {
        img:"./e_bike images/zoom61fcac0beb47d.webp",
        name:" kinetic-green zoom",
        price:" 82,500*",
        Max_Speed:"40kmph",
        Range: "100km/charge",
        Battery_capacity:"60v",
    },
    {
        img:"./e_bike images/reo5fbcd02994358.webp",
        name:" ampere reo",
        price:" 61,999*",
        Max_Speed:"25kmph",
        Range: "58km/charge",
        Battery_capacity:"48v",
    },
    {
        img:"./e_bike images/v_e-star-std1529918580.jpg",
        name:"  avon e star",
        price:" 60,000*",
        Max_Speed:"50kmph",
        Range: "65km/charge",
        Battery_capacity:"48v",
    },

]