export default [
    {
        img:"./petrol cars images/exterior-right-front-three-quarter-10.webp",
        name:" maruti suzuki",
        price:" 15.91 lakh*",
        mileage:"  22.38 to 30.9 kmpl",
        transmission:"Manual&automatic",
        capacity:"5",
    },
    {
        img:"./petrol cars images/vitara-brezza-2022-exterior-right-front-three-quarter.webp",
        name:" maruti brezza",
        price:" 7.99 lakh*",
        mileage:"  19.8 to 19.9 kmpl",
        transmission:"Manual&automatic",
        capacity:"5",
    },
    {
        img:"./petrol cars images/MercedesBenz-GClass-Exterior-137816.webp",
        name:" Mercedes-Benz G",
        price:" 1.72 Cr*",
        mileage:"  6.1 to 9.2 kmpl",
        transmission:"Manual&automatic",
        capacity:"5",
    },
    {
        img:"./petrol cars images/exterior-right-front-three-quarter.webp",
        name:" Mercedes-Benz GLS",
        price:" 2.80 Cr*",
        mileage:"  8.5 kmpl",
        transmission:"automatic",
        capacity:"5",
    },
    {
        img:"./petrol cars images/exterior-right-front-three-quarter-2.webp",
        name:" Citroen C3",
        price:" price=5.88 lakh*",
        mileage:"  19.4 to 19.8 kmpl",
        transmission:"Manual",
        capacity:"5",
    },
    {
        img:"./petrol cars images/scorpio-n-exterior-right-front-three-quarter-15.webp",
        name:" Mahindra Scorpio-N",
        price:" 11.99 lakh*",
        mileage:"  15.5kmpl",
        transmission:"Manual&automatic",
        capacity:"6 & 7",
    },
    {
        img:"./petrol cars images/thar-exterior-right-front-three-quarter-11.webp",
        name:"Mahindra Thar",
        price:" 13.58 lakh*",
        mileage:"  14.56kmpl",
        transmission:"Manual&automatic",
        capacity:"4",
    },
    {
        img:"./petrol cars images/fortuner-exterior-right-front-three-quarter-19.webp",
        name:" Toyota Fortuner",
        price:" 32.58  lakh*",
        mileage:"  10 to 14.4kmpl",
        transmission:"Manual&automatic",
        capacity:"7",
    },
    {
        img:"./petrol cars images/all-new-city-exterior-right-front-three-quarter.webp",
        name:" Honda All New City",
        price:" 11.60  lakh*",
        mileage:"  17.8 to 24.1kmpl",
        transmission:"Manual&automatic",
        capacity:"5",
    },
    {
        img:"./petrol cars images/lx-exterior-right-front-three-quarter.webp",
        name:" Lexus LX",
        price:" 2.33 Crore",
        mileage:"  6.9kmpl",
        transmission:"automatic",
        capacity:"7",
    },
    {
        img:"./petrol cars images/Porsche-992-911-Right-Front-Three-Quarter-154380.webp",
        name:" Porsche 911",
        price:" 1.72 Crore",
        mileage:"  11.02kmpl",
        transmission:"automatic",
        capacity:"2",
    },
    {
        img:"./petrol cars images/MercedesBenz-CClass-Cabriolet-Exterior-139428.webp",
        name:" Mercedes-Benz ",
        price:" 70.64 Lakh",
        mileage:" 12.02kmpl",
        transmission:"automatic",
        capacity:"4",
    },
    {
        img:"./petrol cars images/maybach-s-class-exterior-right-front-three-quarter.webp",
        name:" Mercedes-Benz E",
        price:"2.50 Crore*",
        mileage:"  9.8kmpl",
        transmission:"automatic",
        capacity:"4",
    },
    {
        img:"./petrol cars images/e-class-exterior-right-front-three-quarter.webp",
        name:" Mercedes-Benz E",
        price:" 66.99 Lakh*",
        mileage:"  9.02kmpl",
        transmission:"automatic",
        capacity:"4",
    },
    {
        img:"./petrol cars images/innova-crysta-exterior-right-front-three-quarter-3.webp",
        name:" Toyota Innova",
        price:" 18.09 Lakh*",
        mileage:"  10.2 to 15.6 kmpl",
        transmission:"Manual&automatic",
        capacity:"7 - 8",
    },
]