export default [
    {
        img:"./scooter images/x.pagespeed.ic.vYLHQ7kk5I.jpg",
        name:" honda activa 6g",
        price:" 73,531 on road*",
        capacity:"110CC",
        mileage:"50kmpl",
        tank_capacity:"5.3L",
    },
    {
        img:"./scooter images/x.pagespeed.ic.2WTHwbFWDZ.jpg",
        name:"  TVS ntorq 125 ",
        price:" 85,427 on road*",
        capacity:"124.8CC",
        mileage:"45 to 50kmpl",
        tank_capacity:"5.8L",
    },
    {
        img:"./scooter images/x.pagespeed.ic.w6wTJ2SyBl.jpg",
        name:" suzuki access ",
        price:" 85,427 on road*",
        capacity:"124.8CC",
        mileage:"50kmpl",
        tank_capacity:"5.8L",
    },
    {
        img:"./scooter images/x.pagespeed.ic.HVyOUw2Ndy.jpg",
        name:"  TVS JUPITER",
        price:" 73,097 on road*",
        capacity:"109.7CC",
        mileage:"50kmpl",
        tank_capacity:"7L",
    },
    {
        img:"./scooter images/x.pagespeed.ic.VF6KuEplL5.jpg",
        name:" Yamaha YZF R1   ",
        price:" 78,963 on road*",
        capacity:"125CC",
        mileage:"50.5kmpl",
        tank_capacity:"5.2L",
    },
    {
        img:"./scooter images/x.pagespeed.ic.uk7RC29IZI.jpg",
        name:" honda activa 125 ",
        price:" 78,084 on road*",
        capacity:"124CC",
        mileage:"46.5kmpl",
        tank_capacity:"5.3L",
    },
    {
        img:"./scooter images/x.pagespeed.ic.guYp9rBKBr.jpg",
        name:" honda dio  ",
        price:" 71,371 on road*",
        capacity:"109.51CC",
        mileage:"48kmpl",
        tank_capacity:"5.8L",
    },
    {
        img:"./scooter images/x.pagespeed.ic.EA0-R2GPLd.jpg",
        name:" Suzuki Burgman",
        price:" 89,298 on road*",
        capacity:"124CC",
        mileage:"50kmpl",
        tank_capacity:"5.5L",
    },
    {
        img:"./scooter images/download (1).jpeg",
        name:" hero maestro edge 125 ",
        price:" 82,196 on road*",
        capacity:"124.6CC",
        mileage:"45kmpl",
        tank_capacity:"5L",
    },
    {
        img:"./scooter images/x.pagespeed.ic.yKtRoIdPxD.jpg",
        name:" suzuki avenis 125",
        price:" 89,672 on road*",
        capacity:"124CC",
        mileage:"54kmpl",
        tank_capacity:"5.2L",
    },
    {
        img:"./scooter images/x.pagespeed.ic.pxGuCIv_sT.jpg",
        name:" tvs cooty zest 110 ",
        price:" 73,002 on road*",
        capacity:"109.7CCC",
        mileage:"45kmpl",
        tank_capacity:"5L",
    },
    {
        img:"./scooter images/x.pagespeed.ic.ZRBkQ5YaF6.jpg",
        name:" hero pleasure ",
        price:" 67,898 on road*",
        capacity:"110.9CC",
        mileage:"50kmpl",
        tank_capacity:"4.8L",
    },
    {
        img:"./scooter images/x.pagespeed.ic.2u0WT9HQsd.jpg",
        name:" tvs scooty pep plus ",
        price:" 63,514 on road*",
        capacity:" 87.8CC",
        mileage:"50kmpl",
        tank_capacity:"4.2L",
    },
    {
        img:"./scooter images/ray-zr-125619c74ef1b391.webp",
        name:"  yamaha rayzr 125  ",
        price:" 80,730 - 30,130on road*",
        capacity:"125CC",
        mileage:"50kmpl",
        tank_capacity:"20.7L",
    },
    {
        img:"./scooter images/destini-1256246b7719af18.webp",
        name:"hero destini-125 ",
        price:" 71,108 - 82,908 on road*",
        capacity:"124.6CC",
        mileage:"54kmpl",
        tank_capacity:"5L",
    },

]